# Generated by Django 5.1.3 on 2024-12-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Babysitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('experience_years', models.IntegerField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bio', models.TextField()),
                ('certifications', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('availability', models.CharField(choices=[('full_time', 'Temps plein'), ('part_time', 'Temps partiel'), ('occasional', 'Occasionnel')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('number_of_children', models.IntegerField()),
                ('children_ages', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
