# Generated by Django 5.1.3 on 2024-12-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysitters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='babysitter',
            name='password',
            field=models.CharField(default='default_password', max_length=255),
        ),
        migrations.AddField(
            model_name='parent',
            name='password',
            field=models.CharField(default='default_password', max_length=255),
        ),
    ]
