# Generated by Django 5.1.3 on 2024-12-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysitters', '0003_remove_babysitter_password_remove_parent_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='babysitter',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='babysitter',
            name='languages_spoken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='babysitter',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='babysitter',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='babysitter',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='availability',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
