# Generated by Django 5.1.3 on 2024-12-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysitters', '0004_babysitter_city_babysitter_languages_spoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='babysitter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='babysitter_photos/'),
        ),
    ]
