# Generated by Django 5.1.3 on 2024-12-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysitters', '0006_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='photo',
            field=models.ImageField(blank=True, default='babysitter_photos/avatar.jpg', null=True, upload_to='babysitter_photos/'),
        ),
    ]
