# Generated by Django 5.1.3 on 2024-12-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysitters', '0007_alter_babysitter_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='photo',
            field=models.ImageField(blank=True, default='static/babysitter_photos/avatar.jpg', null=True, upload_to='static/babysitter_photos/'),
        ),
    ]
