# Generated by Django 5.1.3 on 2024-12-25 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysitters', '0013_alter_notification_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='babysitters.parent'),
        ),
    ]
