# Generated by Django 5.1.3 on 2024-12-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysitters', '0015_remove_notification_read_notification_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
